### ISSUE TITLE
Refresh build link

### ISSUE THREAD

**Issue by delucks** [bchavez/SharpFlame#14]
Hey there, I'm excited to try out SharpFlame. I'm trying to run on Linux and while build should hypothetically work, I can't get the project to build on my system. Since the last CI build was more than 6 months ago, the build link on the README does not contain any artifacts. Could you create a dummy commit to refresh the CI and create new artifacts? Thanks!

**Comment by bchavez** [comment]
Hi Jamie,

I re-ran the build; here's the current artifacts: https://ci.appveyor.com/project/bchavez/sharpflame/build/artifacts

Hope that helps,
Brian

**Comment by bchavez** [comment]
Also, just a quick note. SharpFlame **barely** works. You should really use Flame if you want to do anything production worthy with WZ.
